spring:
 mail:
  host: smtp.gmail.com
  username: sabaympl@gmail.com
  password: crydpspyxpvmvgdl
  port: 587
  properties:
    mail:
     smtp:
      starttls:
       enable: true
      auth: true
     